name: 'wait-for-mina-network'
description: 'GitHub Action to wait for the Mina network readiness'
author: 'O(1) Labs'

branding:
  icon: 'clock'
  color: 'green'

inputs:
  mina-graphql-port:
    required: false
    description: 'Mina GraphQL port'
    default: '3085'
  max-attempts:
    required: false
    description: 'Maximum number of attempts'
    default: '60'
  polling-interval-ms:
    required: false
    description: 'Polling interval in milliseconds'
    default: '10000'

runs:
  using: 'node20'
  main: 'dist/index.js'
